---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: haproxy-test
    app.kubernetes.io/managed-by: helm
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: haproxy
  ports:
    - nodePort: {{ .Values.haproxyNodePort }}
      port: 80
      targetPort: 80
