---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: haproxy
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: haproxy-test
    app.kubernetes.io/managed-by: helm
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: haproxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: haproxy
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/component: haproxy-test
        app.kubernetes.io/managed-by: helm
    spec:
      containers:
        - name: haproxy
          image: {{ .Values.haproxyImage }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config
              mountPath: /usr/local/etc/haproxy
          ports:
            - containerPort: 80
      volumes:
        - name: config
          configMap:
            name: haproxy
