---
apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: haproxy-test
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    app.kubernetes.io/name: node
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
