---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: node
    app.kubernetes.io/version: {{ .Chart.Version }}
    app.kubernetes.io/component: haproxy-test
    app.kubernetes.io/managed-by: helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node
  serviceName: node
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node
        app.kubernetes.io/version: {{ .Chart.Version }}
        app.kubernetes.io/component: haproxy-test
        app.kubernetes.io/managed-by: helm
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          imagePullPolicy: IfNotPresent
          env:
            - name: HAT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 8080
